from pathlib import Path

from openpyxl import Workbook, load_workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.table import Table, TableStyleInfo


OUTPUT = Path("docs/research/us_public_battle_spectrum_baseline.xlsx")


BATTLE_CASES = [
    {
        "case_id": "CASE-DS-1991",
        "operation": "Operation Desert Shield / Desert Storm",
        "year_range": "1990-1991",
        "mission_type": "联合地面机动、航空支援、指挥控制、火力协同",
        "spectrum_dependent_tasks": "地面战斗网话音；航空空空/空地通信；跨网指挥；抗干扰通信",
        "public_systems": "SINCGARS；安全FM；UHF航空通信；VHF/FM航空通信",
        "observed_issue_or_result": "SINCGARS公开资料称在西南亚环境表现良好；Apache事件调查显示空地无线电域存在互通边界。",
        "planning_requirements": "多频段装备建模；空地兼容性；跨网网关；备用链路；距离与优先级约束",
        "parameter_disclosure": "系统级参数公开；行动实际频道未公开",
        "confidence": "高",
        "source_org": "U.S. Army / GAO",
        "source_title": "1992 Weapon Systems Handbook; Operation Desert Storm: Apache Helicopter Fratricide Incident",
        "source_url": "https://asc.army.mil/docs/wsh2/1992-wsh.pdf | https://www.gao.gov/assets/osi-93-4.pdf",
        "evidence_note": "不能将调查中披露的无线电类别解释为事故唯一原因。",
    },
    {
        "case_id": "CASE-OAF-1999",
        "operation": "Operation Allied Force / Task Force Hawk",
        "year_range": "1999",
        "mission_type": "Apache深袭特遣部队支援联合空中战役",
        "spectrum_dependent_tasks": "陆空协同；C4I互操作；共同态势信息交换",
        "public_systems": "报告未在公开摘要中披露具体电台和频道",
        "observed_issue_or_result": "GAO确认陆军和空军在联合作战及C4I装备互操作方面存在显著问题。",
        "planning_requirements": "通信链路实体；跨军种网关；互操作覆盖率；共同态势数据可达性",
        "parameter_disclosure": "任务与问题公开；频率参数未公开",
        "confidence": "高",
        "source_org": "GAO",
        "source_title": "GAO-01-401 Kosovo Air Operations",
        "source_url": "https://www.gao.gov/products/gao-01-401",
        "evidence_note": "不得用Link 16等系统通用频段冒充Task Force Hawk实际频道。",
    },
    {
        "case_id": "CASE-OEF-2001",
        "operation": "Operation Enduring Freedom",
        "year_range": "2001起",
        "mission_type": "山地远距离作战、分散节点指挥、ISR与超视距通信",
        "spectrum_dependent_tasks": "超视距指挥；战术卫星通信；地面视距通信；ISR数据传输",
        "public_systems": "UHF TACSAT；MSE/JNN/WIN-T演进背景",
        "observed_issue_or_result": "山地环境限制视距FM通信；OEF推动超视距网络需求。",
        "planning_requirements": "视距可达性；地形遮挡等级；卫星/HF备用链路；关键任务多链路保障",
        "parameter_disclosure": "业务频段类别公开；行动频道未公开",
        "confidence": "中高",
        "source_org": "U.S. Army",
        "source_title": "WIN-T: It's real, it's here and it works; High-Frequency Communications",
        "source_url": "https://www.army.mil/article/25076/warfighter_information_network_tactical_its_real_its_here_and_it_works | https://www.lineofdeparture.army.mil/Journals/Field-Artillery/Field-Artillery-Archive/Field-Artillery-2025-E-Edition/High-Frequency-Communications/",
        "evidence_note": "UHF在公开文章中仅按300 MHz-3 GHz类别描述，不等于具体TACSAT频道。",
    },
    {
        "case_id": "CASE-OIF-2003",
        "operation": "Operation Iraqi Freedom",
        "year_range": "2003起",
        "mission_type": "高速地面推进、机动指挥、宽带态势共享",
        "spectrum_dependent_tasks": "超视距骨干；指挥所宽带；行进间通信；共同态势图",
        "public_systems": "MSE；JNN；WIN-T；卫星与地面网络",
        "observed_issue_or_result": "进攻速度超过原MSE视距网络通信能力，推动JNN/WIN-T超视距网络。",
        "planning_requirements": "作战阶段与时段；机动速度；建链/撤收时间；行进间能力；链路切换代价",
        "parameter_disclosure": "架构和能力公开；行动频道未公开",
        "confidence": "高",
        "source_org": "U.S. Army / GAO",
        "source_title": "WIN-T: It's real, it's here and it works; GAO-04-547 Military Operations",
        "source_url": "https://www.army.mil/article/25076/warfighter_information_network_tactical_its_real_its_here_and_it_works | https://www.gao.gov/products/gao-04-547",
        "evidence_note": "公开证据支持能力缺口，不提供战术网络初始化数据。",
    },
    {
        "case_id": "CASE-UAS-2001-07",
        "operation": "Iraq/Afghanistan UAS Operations",
        "year_range": "2001-2007",
        "mission_type": "无人机飞控、ISR载荷数据回传、实时视频、时敏目标支持",
        "spectrum_dependent_tasks": "飞行控制链路；载荷数据链路；卫星/视距回传；空域协同",
        "public_systems": "多型UAS使用C band或Ku band；Common Data Link改进方向",
        "observed_issue_or_result": "频谱拥塞、互操作和带宽约束导致部分任务延迟；载荷数据需求高于飞控。",
        "planning_requirements": "飞控与载荷链路拆分；带宽需求；同时在线数量；频段重构；拥塞事件动态重筹",
        "parameter_disclosure": "频段类别公开；行动具体频率未公开",
        "confidence": "高",
        "source_org": "GAO",
        "source_title": "GAO-06-49; GAO-07-836 Unmanned Aircraft Systems",
        "source_url": "https://www.gao.gov/products/gao-06-49 | https://www.gao.gov/products/gao-07-836",
        "evidence_note": "数值频率保持为空；不使用IEEE通用波段边界替代战例事实。",
    },
    {
        "case_id": "CASE-MOSUL-2016-17",
        "operation": "Battle of Mosul / Operation Eagle Strike",
        "year_range": "2016-2017",
        "mission_type": "多国联合城市作战、顾问支援、ISR、火力协同和反无人机防护",
        "spectrum_dependent_tasks": "联合指挥通信；无人机侦察；反无人机探测与处置；火力和空域协同；电子战计划",
        "public_systems": "UAS/C-UAS；AUDS；联合通信和电子战能力（具体频道未公开）",
        "observed_issue_or_result": "陆军研究指出频谱持续变化且需要跨参谋协调；部分C-UAS能力会同时影响友军与对手系统，新装备集成和机动部署需要快速适配。",
        "planning_requirements": "城市遮挡；高密度发射源；友军干扰约束；UAS/C-UAS联动；保护区；阶段化资源重筹",
        "parameter_disclosure": "任务、能力类别和冲突现象公开；行动频道、干扰参数和部署坐标未公开",
        "confidence": "高",
        "source_org": "U.S. Army TRADOC",
        "source_title": "Mosul Study Group: What the Battle for Mosul Teaches the Force",
        "source_url": "https://api.army.mil/e2/c/downloads/2023/01/19/e9325e8b/17-24u-mosul-study-group-what-the-battle-for-mosul-teaches-the-force-sep-17-public.pdf",
        "evidence_note": "战例用于提取拥塞、友军兼容和动态适配需求，不复原任何实际电子战配置。",
    },
    {
        "case_id": "CASE-SYRIA-EMS-2018",
        "operation": "Operation Inherent Resolve - Syria contested EMS",
        "year_range": "2018",
        "mission_type": "反恐支援、空地协同和受干扰环境下的分布式行动",
        "spectrum_dependent_tasks": "地面与空中指挥通信；卫星通信；ISR回传；电子支援与电子攻击协同",
        "public_systems": "EC-130H Compass Call；战术通信和卫星通信类别（具体参数未公开）",
        "observed_issue_or_result": "空军公开Compass Call在OIR执行通信对抗任务；GAO引用公开评估称叙利亚环境中的美军通信系统曾经常受到压制。",
        "planning_requirements": "PACE多链路；链路失效事件；优先级降级；断续可用性；重传和任务连续性；跨域协同",
        "parameter_disclosure": "任务和受干扰现象公开；压制频率、效果门限和战术配置未公开",
        "confidence": "中高",
        "source_org": "U.S. Air Force / GAO",
        "source_title": "Compass Call dominates OIR with electronic warfare; GAO-21-64 Electromagnetic Spectrum Operations",
        "source_url": "https://www.af.mil/News/Features/Article/1295655/compass-call-dominates-oir-with-electronic-warfare/ | https://www.gao.gov/assets/gao-21-64.pdf",
        "evidence_note": "只建模通信失效和恢复，不收录电子攻击任务数据。",
    },
    {
        "case_id": "CASE-OAR-2021",
        "operation": "Operation Allies Refuge - Kabul evacuation",
        "year_range": "2021",
        "mission_type": "受威胁机场条件下的大规模非战斗人员撤离和跨洲战略空运",
        "spectrum_dependent_tasks": "机场管制；航空空地通信；联合与多国指挥；航班调度；跨洲空运态势共享",
        "public_systems": "C-17/C-130空运体系；机场空管；军用和商业航空协同（具体频道未公开）",
        "observed_issue_or_result": "美军接管机场空中交通管制并在17天内组织昼夜空运；高峰期约每34分钟一架军机离场，商业和盟国航空力量同时参与。",
        "planning_requirements": "高密度时隙；空地链路优先级；机场局部拥塞；多国互操作；节点突增；应急医疗和威胁事件重筹",
        "parameter_disclosure": "任务规模、节奏和节点类型公开；通信网络配置和航班频道未公开",
        "confidence": "高",
        "source_org": "U.S. Department of Defense / U.S. Transportation Command",
        "source_title": "Transportation Command Aids in Historic Evacuation; Joint Statement on Afghanistan",
        "source_url": "https://www.defense.gov/News/News-Stories/Article/Article/2764916/transportation-command-aids-in-historic-evacuation/ | https://www.defense.gov/News/Releases/Release/Article/2732053/joint-statement-from-the-department-of-state-and-department-of-defense-update-o/",
        "evidence_note": "航班节奏用于构造合成时段，不对应真实频率或历史航班表。",
    },
    {
        "case_id": "CASE-OPG-2023-24",
        "operation": "Red Sea air defense / Operation Prosperity Guardian",
        "year_range": "2023-2024（本批来源截点）",
        "mission_type": "多国海上护航、商船态势协同和舰队防空反导",
        "spectrum_dependent_tasks": "舰载探测跟踪；防空火控；多国指挥；商船双向通信；海上态势共享",
        "public_systems": "舰载雷达、战术数据链、卫星通信和商业海事通信类别（单舰配置未统一公开）",
        "observed_issue_or_result": "行动面对无人机、导弹和无人水面艇威胁；官方强调狭窄繁忙航道、多国协同以及商船过航前后的持续双向通信。",
        "planning_requirements": "舰船机动；航道拥塞；传感器覆盖重叠；多目标突发；多国互操作；商军通信隔离；动态防空优先级",
        "parameter_disclosure": "行动环境和任务类别公开；交战频道、雷达模式和武器控制数据未公开",
        "confidence": "高",
        "source_org": "U.S. Department of Defense / U.S. Navy",
        "source_title": "NAVCENT press briefing on Operation Prosperity Guardian; Navy's Top Officer Credits Training and Logistics",
        "source_url": "https://www.defense.gov/News/Transcripts/Transcript/Article/3631484/navcent-commander-vice-admiral-brad-cooper-holds-an-off-camera-on-the-record-pr/ | https://www.defense.gov/News/News-Stories/Article/Article/3723681/navys-top-officer-credits-training-logistics-with-meeting-red-sea-mission/ | https://www.navy.mil/Press-Office/News-Stories/display-news/Article/3984206/uss-carney-a-destroyer-at-war/",
        "evidence_note": "作为海上多目标防护和联盟互操作场景，不推定参战舰艇的具体传感器配置。",
    },
    {
        "case_id": "CASE-OIR-CUAS-2023-24",
        "operation": "Operation Inherent Resolve - base C-UAS defense",
        "year_range": "2023-2024",
        "mission_type": "伊拉克、叙利亚和科威特方向的基地防护与分层反无人机作战",
        "spectrum_dependent_tasks": "Q-50/Q-53/Q-64探测；FAAD C2融合；联合数据网态势共享；敌我识别；基地告警",
        "public_systems": "AN/TPQ-50、AN/TPQ-53、AN/MPQ-64、FS-LIDS、FAAD C2、Joint Data Network",
        "observed_issue_or_result": "陆军复盘显示多类传感器可形成旅级冗余覆盖并向连级共享近实时态势，但数字架构依赖专业人员和承包商，训练与操作人员数量成为约束。",
        "planning_requirements": "多传感器覆盖；融合节点容量；网络互操作；操作员负荷；固定/机动防护；序列或集群威胁下的优先级",
        "parameter_disclosure": "系统关系、部署周期和组织问题公开；目标轨迹、雷达模式、交战规则和频道未公开",
        "confidence": "高",
        "source_org": "U.S. Army Military Review",
        "source_title": "C-UAS Operations",
        "source_url": "https://www.armyupress.army.mil/Portals/7/military-review/Archives/English/JA-24/C-UAS%20Operations/C-UAS-Operations-UA.pdf",
        "evidence_note": "只提取多传感器融合和人员/网络约束，不构造真实目标轨迹或交战倒计时。",
    },
    {
        "case_id": "EX-PC-C4-2024",
        "operation": "Project Convergence Capstone 4",
        "year_range": "2024",
        "mission_type": "美军各军种与多国伙伴联合网络和CJADC2实验",
        "spectrum_dependent_tasks": "传感器-决策者-效应器数据交换；联盟共同态势；联合火力；远程和受限环境通信",
        "public_systems": "现役通信装备与实验网络混合架构；商业通信方法；互操作枢纽",
        "observed_issue_or_result": "超过4000名参与者通过混合网络验证跨军种和多国数据交换；官方将受干扰、偏远环境和互操作列为持续挑战。",
        "planning_requirements": "多级网络；异构链路；带宽受限；伙伴接入策略；节点失联；数据优先级；低特征和机动指挥所",
        "parameter_disclosure": "实验目标、参与规模和网络类别公开；具体频道和实验网络配置未公开",
        "confidence": "高",
        "source_org": "U.S. Department of Defense / U.S. Army",
        "source_title": "Network Capability Provides Successful Start to Project Convergence Capstone 4",
        "source_url": "https://www.defense.gov/News/News-Stories/Article/Article/3692858/network-capability-provides-successful-start-to-project-convergence-capstone-4/",
        "evidence_note": "明确标记为联合实验，不作为实战结果统计。",
    },
]


CASE_METADATA = {
    "CASE-DS-1991": ("combat_operation", "部署准备；空中战役；地面进攻；巩固", "机动推进；空地协同变化；链路中断", "SRC-01; SRC-02"),
    "CASE-OAF-1999": ("combat_operation", "部署；空中战役；Apache特遣行动准备", "跨军种互操作故障；任务调整", "SRC-03"),
    "CASE-OEF-2001": ("combat_operation", "远程进入；分散行动；持续保障", "地形遮挡；节点分散；超视距需求变化", "SRC-07"),
    "CASE-OIF-2003": ("combat_operation", "快速推进；城市作战；稳定行动", "机动速度变化；节点重构；链路切换", "SRC-04; SRC-07"),
    "CASE-UAS-2001-07": ("cross_operation_case", "飞控准备；任务执行；载荷回传", "频谱拥塞；带宽降级；任务延迟", "SRC-05; SRC-06"),
    "CASE-MOSUL-2016-17": ("combat_operation", "包围塑造；东摩苏尔；西摩苏尔；巩固", "UAS威胁增长；C-UAS机动；友军干扰；装备快速接入", "SRC-25"),
    "CASE-SYRIA-EMS-2018": ("combat_operation", "任务准备；受干扰执行；链路恢复", "通信压制；SATCOM受扰；链路降级与切换", "SRC-26; SRC-27"),
    "CASE-OAR-2021": ("noncombatant_evacuation", "机场夺控；兵力增援；昼夜撤离；撤收", "航班激增；威胁事件；伤员后送；多国节点加入", "SRC-28; SRC-29"),
    "CASE-OPG-2023-24": ("combat_operation", "联盟建立；持续护航；威胁拦截；补给轮换", "无人机/导弹/无人艇突发；商船流量变化；伙伴加入", "SRC-30; SRC-31; SRC-32"),
    "CASE-OIR-CUAS-2023-24": ("combat_operation", "部署准备；基地防护建立；持续值班；轮换复盘", "多目标突发；传感器离线；融合节点负荷；人员短缺", "SRC-44"),
    "EX-PC-C4-2024": ("joint_experiment", "网络建立；风险降低；两阶段实验；复盘", "节点失联；带宽受限；伙伴接入；数据优先级变化", "SRC-33"),
}

for battle_case in BATTLE_CASES:
    case_type, phase_model, dynamic_events, source_ids = CASE_METADATA[battle_case["case_id"]]
    battle_case["case_type"] = case_type
    battle_case["phase_model"] = phase_model
    battle_case["dynamic_events"] = dynamic_events
    battle_case["source_ids"] = source_ids


PUBLIC_PARAMETERS = [
    {
        "parameter_id": "PAR-SINCGARS",
        "system_or_service": "SINCGARS",
        "mission_role": "地面战斗网指挥控制",
        "case_links": "CASE-DS-1991",
        "frequency_start_mhz": 30.0,
        "frequency_end_mhz": 87.975,
        "center_frequency_mhz": None,
        "channel_step_khz": 25.0,
        "occupied_bandwidth_khz": None,
        "power_w": None,
        "channel_count": 2320,
        "range_km": "8-35",
        "waveform_or_access": "单信道/跳频能力；ECCM",
        "mobility": "背负、车载、机载",
        "assignment_mode": "离散频道",
        "planning_relation": "战斗网；按任务和网系分配",
        "parameter_status": "公开精确范围",
        "confidence": "高",
        "source_org": "U.S. Army",
        "source_title": "1992 Weapon Systems Handbook",
        "source_url": "https://asc.army.mil/docs/wsh2/1992-wsh.pdf",
        "evidence_note": "25 kHz步进与公开端点及2320个等间隔频道一致；不同型号功率未统一。",
        "usage_boundary": "系统调谐范围，不是行动实际频道，不得直接标记为可用频段。",
    },
    {
        "parameter_id": "PAR-MIL-AIR-VOICE",
        "system_or_service": "军用航空空地话音参考",
        "mission_role": "军机空地/空空话音和空管协调",
        "case_links": "CASE-DS-1991; CASE-OAF-1999",
        "frequency_start_mhz": 225.0,
        "frequency_end_mhz": 399.9,
        "center_frequency_mhz": None,
        "channel_step_khz": 25.0,
        "occupied_bandwidth_khz": 6.0,
        "power_w": "10-50",
        "channel_count": 471,
        "range_km": None,
        "waveform_or_access": "公开规划资料未统一给出；按航空话音业务建模",
        "mobility": "机载/地面站",
        "assignment_mode": "离散频道",
        "planning_relation": "航空业务，需空地互操作",
        "parameter_status": "公开业务规划范围",
        "confidence": "中高",
        "source_org": "U.S. Department of Transportation / NTIA",
        "source_title": "Transportation Strategic Spectrum Plan",
        "source_url": "https://www.ntia.gov/sites/default/files/publications/transportation_strategic_spectrum_plan_nov2007_0.pdf",
        "evidence_note": "公开资料说明排除326.6-335.4 MHz；471频道是ATS规划口径。",
        "usage_boundary": "美国境内规划资料，不代表海外战例授权。",
    },
    {
        "parameter_id": "PAR-EPLRS",
        "system_or_service": "EPLRS/AEPLRS",
        "mission_role": "战术位置报告、数据分发、态势感知",
        "case_links": "CASE-OAF-1999; CASE-OIF-2003",
        "frequency_start_mhz": 420.0,
        "frequency_end_mhz": 450.0,
        "center_frequency_mhz": None,
        "channel_step_khz": None,
        "occupied_bandwidth_khz": None,
        "power_w": None,
        "channel_count": None,
        "range_km": "公开报告仅称支持短程和长程",
        "waveform_or_access": "TDMA；跳频扩频；多跳",
        "mobility": "地面、舰载、机载",
        "assignment_mode": "网络化跳频资源",
        "planning_relation": "位置报告和战术数据网络",
        "parameter_status": "公开精确范围",
        "confidence": "高",
        "source_org": "NTIA",
        "source_title": "420-450 MHz Federal Spectrum Use Report",
        "source_url": "https://www.ntia.gov/files/ntia/publications/compendium/0420.00-0450.00_01MAY15.pdf",
        "evidence_note": "报告明确EPLRS/AEPLRS用途和波形类别。",
        "usage_boundary": "公共系统频段，实际网络参数和跳频表未公开。",
    },
    {
        "parameter_id": "PAR-LINK16",
        "system_or_service": "JTIDS/MIDS / Link 16",
        "mission_role": "联合战术数据、语音和态势感知",
        "case_links": "CASE-OAF-1999; CASE-OIF-2003",
        "frequency_start_mhz": 960.0,
        "frequency_end_mhz": 1164.0,
        "center_frequency_mhz": None,
        "channel_step_khz": None,
        "occupied_bandwidth_khz": None,
        "power_w": None,
        "channel_count": 51,
        "range_km": "视距",
        "waveform_or_access": "扩频跳频；TDMA类多址；内部加密",
        "mobility": "机载、舰载、地面",
        "assignment_mode": "51个离散频率上的网络化时隙",
        "planning_relation": "联合数据链，需与航空导航业务协调",
        "parameter_status": "公开精确范围",
        "confidence": "高",
        "source_org": "NTIA / U.S. Army",
        "source_title": "1164-1215 MHz Federal Spectrum Use Report; FM 3-01",
        "source_url": "https://www.ntia.gov/files/ntia/publications/compendium/1164.00-1215.00_01MAR14.pdf | https://rdl.train.army.mil/catalog-ws/view/100.ATSC/C01CC9C1-DA1C-4D5E-A6EB-5FCFAE218DCD-1398170439966/fm3_01.pdf",
        "evidence_note": "FM 3-01公开数据率超过50 kbit/s和51个离散频率；NTIA明确960-1164 MHz边界。",
        "usage_boundary": "不收录网络号、时隙分配、密钥或脉冲去冲突参数。",
    },
    {
        "parameter_id": "PAR-GPS-L5",
        "system_or_service": "GPS L5",
        "mission_role": "定位、导航和授时保护对象",
        "case_links": "CASE-OEF-2001; CASE-OIF-2003",
        "frequency_start_mhz": None,
        "frequency_end_mhz": None,
        "center_frequency_mhz": 1176.45,
        "channel_step_khz": None,
        "occupied_bandwidth_khz": 24000,
        "power_w": None,
        "channel_count": None,
        "range_km": "全球覆盖（接收）",
        "waveform_or_access": "RNSS接收信号",
        "mobility": "各类接收平台",
        "assignment_mode": "中心频率保护",
        "planning_relation": "保护频率/敏感接收业务",
        "parameter_status": "公开中心频率",
        "confidence": "高",
        "source_org": "NTIA",
        "source_title": "1164-1215 MHz Federal Spectrum Use Report",
        "source_url": "https://www.ntia.gov/files/ntia/publications/compendium/1164.00-1215.00_01MAR14.pdf",
        "evidence_note": "NTIA说明L5位于1176.45±12 MHz。",
        "usage_boundary": "用于仿真保护窗口，不代表接收机抗干扰门限。",
    },
    {
        "parameter_id": "PAR-GPS-L2",
        "system_or_service": "GPS L2",
        "mission_role": "定位、导航和授时保护对象",
        "case_links": "CASE-OEF-2001; CASE-OIF-2003",
        "frequency_start_mhz": None,
        "frequency_end_mhz": None,
        "center_frequency_mhz": 1227.60,
        "channel_step_khz": None,
        "occupied_bandwidth_khz": None,
        "power_w": None,
        "channel_count": None,
        "range_km": "全球覆盖（接收）",
        "waveform_or_access": "RNSS接收信号",
        "mobility": "各类接收平台",
        "assignment_mode": "中心频率保护",
        "planning_relation": "保护频率/敏感接收业务",
        "parameter_status": "公开中心频率",
        "confidence": "高",
        "source_org": "NTIA",
        "source_title": "1164-1215 MHz Federal Spectrum Use Report",
        "source_url": "https://www.ntia.gov/files/ntia/publications/compendium/1164.00-1215.00_01MAR14.pdf",
        "evidence_note": "NTIA公开L2中心频率。",
        "usage_boundary": "不得推定军用码型、功率或抗干扰参数。",
    },
    {
        "parameter_id": "PAR-GPS-L1",
        "system_or_service": "GPS L1",
        "mission_role": "定位、导航和授时保护对象",
        "case_links": "CASE-OEF-2001; CASE-OIF-2003",
        "frequency_start_mhz": None,
        "frequency_end_mhz": None,
        "center_frequency_mhz": 1575.42,
        "channel_step_khz": None,
        "occupied_bandwidth_khz": None,
        "power_w": None,
        "channel_count": None,
        "range_km": "全球覆盖（接收）",
        "waveform_or_access": "RNSS接收信号",
        "mobility": "各类接收平台",
        "assignment_mode": "中心频率保护",
        "planning_relation": "保护频率/敏感接收业务",
        "parameter_status": "公开中心频率",
        "confidence": "高",
        "source_org": "NTIA",
        "source_title": "1164-1215 MHz Federal Spectrum Use Report",
        "source_url": "https://www.ntia.gov/files/ntia/publications/compendium/1164.00-1215.00_01MAR14.pdf",
        "evidence_note": "NTIA公开L1中心频率。",
        "usage_boundary": "不得推定军用码型、功率或抗干扰参数。",
    },
    {
        "parameter_id": "PAR-UAS-C-KU",
        "system_or_service": "UAS飞控/载荷链路（公开类别）",
        "mission_role": "无人机飞控、传感器数据和视频回传",
        "case_links": "CASE-UAS-2001-07",
        "frequency_start_mhz": None,
        "frequency_end_mhz": None,
        "center_frequency_mhz": None,
        "channel_step_khz": None,
        "occupied_bandwidth_khz": None,
        "power_w": None,
        "channel_count": None,
        "range_km": None,
        "waveform_or_access": "C band / Ku band；具体波形未在GAO摘要公开",
        "mobility": "空中平台/地面控制站",
        "assignment_mode": "飞控与载荷链路分开规划",
        "planning_relation": "高带宽载荷链路与高可靠飞控链路竞争资源",
        "parameter_status": "仅公开频段类别",
        "confidence": "高",
        "source_org": "GAO",
        "source_title": "GAO-06-49 Unmanned Aircraft Systems",
        "source_url": "https://www.gao.gov/products/gao-06-49",
        "evidence_note": "GAO统计12类UAS中C/Ku频段使用情况，并记录拥塞导致任务延迟。",
        "usage_boundary": "数值频率必须保持为空，不能用通用波段定义替代行动数据。",
    },
    {
        "parameter_id": "PAR-TRR-4400",
        "system_or_service": "战术无线电中继研究参考",
        "mission_role": "战术中继、固定/可搬移数据链",
        "case_links": "CASE-OIF-2003",
        "frequency_start_mhz": 4400.0,
        "frequency_end_mhz": 4940.0,
        "center_frequency_mhz": None,
        "channel_step_khz": None,
        "occupied_bandwidth_khz": None,
        "power_w": None,
        "channel_count": None,
        "range_km": None,
        "waveform_or_access": "公开评估未给统一波形",
        "mobility": "可搬移/固定中继",
        "assignment_mode": "连续频段/中继链路",
        "planning_relation": "与CEC、雷达及其他系统共存研究",
        "parameter_status": "公开评估范围",
        "confidence": "中",
        "source_org": "DoD / NTIA",
        "source_title": "DoD 4400-4940 MHz Band Assessment",
        "source_url": "https://www.ntia.gov/sites/default/files/publications/dodassessment_0.pdf",
        "evidence_note": "属于频谱迁移和共存评估，不证明某次战役实际使用该范围。",
        "usage_boundary": "仅供冲突研究，不得直接转成可用规则。",
    },
    {
        "parameter_id": "PAR-RADAR-TPQ53",
        "system_or_service": "AN/TPQ-53反炮兵雷达",
        "mission_role": "迫击炮、火炮和火箭弹探测、分类及发射点定位",
        "case_links": "",
        "frequency_start_mhz": 2000.0,
        "frequency_end_mhz": 4000.0,
        "center_frequency_mhz": None,
        "channel_step_khz": None,
        "occupied_bandwidth_khz": None,
        "power_w": None,
        "channel_count": None,
        "range_km": "90度模式：火箭60、火炮34、迫击炮20；360度模式：20",
        "waveform_or_access": "S波段有源相控阵；具体波形未公开",
        "mobility": "高机动、可部署雷达",
        "assignment_mode": "雷达调谐范围/时段占用",
        "planning_relation": "高优先级雷达发射；需要时空保护和同址兼容",
        "parameter_status": "公开波段与能力范围",
        "confidence": "中高",
        "source_org": "U.S. Army ODIN",
        "source_title": "AN/TPQ-53 Counterfire Target Acquisition Radar",
        "source_url": "https://odin.t2com.army.mil/WEG/Asset/6ea3c7edc1d7b3bab022f375761f3ee6",
        "evidence_note": "ODIN公开2-4 GHz和不同工作模式的最大覆盖距离；未将60 kW电源功率误作射频发射功率。",
        "usage_boundary": "宽波段装备能力记录，不代表战时调谐点、脉冲参数或部署位置。",
    },
    {
        "parameter_id": "PAR-RADAR-SENTINEL",
        "system_or_service": "AN/MPQ-64 Sentinel",
        "mission_role": "低空空情、无人机、巡航导弹及固定/旋翼机监视",
        "case_links": "",
        "frequency_start_mhz": None,
        "frequency_end_mhz": None,
        "center_frequency_mhz": None,
        "channel_step_khz": None,
        "occupied_bandwidth_khz": None,
        "power_w": None,
        "channel_count": None,
        "range_km": "75",
        "waveform_or_access": "三维X波段相控阵；具体频率和波形未公开",
        "mobility": "车载/拖车式、两人操作",
        "assignment_mode": "雷达波段/时段占用",
        "planning_relation": "持续空情监视；与数据链和防空指挥系统协同",
        "parameter_status": "仅公开频段类别和覆盖距离",
        "confidence": "高",
        "source_org": "U.S. Army Acquisition",
        "source_title": "U.S. Army Acquisition Program Portfolio 2024; Acquisition partnership to roll out new improved Sentinel Radar",
        "source_url": "https://api.army.mil/e2/c/downloads/2024/07/19/ab2038a9/u-s-army-portfolio-2024.pdf | https://asc.army.mil/web/access-acquisition-partnership-to-roll-out-new-improved-sentinel-radar/",
        "evidence_note": "陆军公开资料明确X波段、三维、360度和75 km；数值调谐范围保持为空。75 km和360度由陆军采办文章直接支持。",
        "usage_boundary": "不得用通用X波段边界替代具体授权范围。",
    },
    {
        "parameter_id": "PAR-RADAR-SURVEILLANCE-2700",
        "system_or_service": "联邦/军用监视雷达参考",
        "mission_role": "机场监视、天气与军用监视雷达共存",
        "case_links": "",
        "frequency_start_mhz": 2700.0,
        "frequency_end_mhz": 2900.0,
        "center_frequency_mhz": None,
        "channel_step_khz": None,
        "occupied_bandwidth_khz": None,
        "power_w": None,
        "channel_count": None,
        "range_km": None,
        "waveform_or_access": "脉冲雷达；具体系统参数依RSEC和单台指配",
        "mobility": "固定、移动或可搬移",
        "assignment_mode": "单台雷达频率与保护区",
        "planning_relation": "高功率雷达之间需频率-距离协调和杂散保护",
        "parameter_status": "公开业务频段",
        "confidence": "高",
        "source_org": "NTIA",
        "source_title": "2700-2900 MHz Federal Spectrum Use Report",
        "source_url": "https://www.ntia.gov/files/ntia/publications/compendium/2700.00-2900.00_01MAR14.pdf",
        "evidence_note": "NTIA强调该频段雷达需谨慎协调并符合Radar Spectrum Engineering Criteria。",
        "usage_boundary": "业务共存参考，不代表平台可在整个频段自由分配。",
    },
    {
        "parameter_id": "PAR-RADAR-MARITIME-2900",
        "system_or_service": "军用/海上搜索雷达参考",
        "mission_role": "海上导航、搜索、跟踪和训练",
        "case_links": "",
        "frequency_start_mhz": 2900.0,
        "frequency_end_mhz": 3100.0,
        "center_frequency_mhz": None,
        "channel_step_khz": None,
        "occupied_bandwidth_khz": None,
        "power_w": None,
        "channel_count": None,
        "range_km": None,
        "waveform_or_access": "脉冲/线性调频雷达类别",
        "mobility": "舰载、岸基、可搬移",
        "assignment_mode": "雷达频率与保护区",
        "planning_relation": "需评估接收机前端过载、带外发射和频率-距离隔离",
        "parameter_status": "公开业务频段",
        "confidence": "高",
        "source_org": "NTIA",
        "source_title": "2900-3100 MHz Federal Spectrum Use Report",
        "source_url": "https://www.ntia.gov/files/ntia/publications/compendium/2900.00-3100.00_01MAY15.pdf",
        "evidence_note": "NTIA公开该频段的军用和海上雷达用途，并说明线性调频等技术。",
        "usage_boundary": "不包含单台雷达峰值功率、脉宽、PRF或部署参数。",
    },
    {
        "parameter_id": "PAR-UHF-SATCOM-DOWN",
        "system_or_service": "FLTSATCOM/UHF移动卫星下行参考",
        "mission_role": "战术和战略窄带卫星通信下行",
        "case_links": "CASE-OEF-2001; CASE-OIF-2003",
        "frequency_start_mhz": 243.855,
        "frequency_end_mhz": 269.95,
        "center_frequency_mhz": None,
        "channel_step_khz": None,
        "occupied_bandwidth_khz": None,
        "power_w": None,
        "channel_count": None,
        "range_km": "卫星覆盖",
        "waveform_or_access": "窄带移动卫星；具体频道和接入计划未公开",
        "mobility": "背负、车载、舰载、机载终端",
        "assignment_mode": "卫星下行频道/网络资源",
        "planning_relation": "超视距关键链路；下行与地面/航空业务共存",
        "parameter_status": "公开精确历史范围",
        "confidence": "高",
        "source_org": "NTIA",
        "source_title": "225-328.6 MHz Federal Spectrum Use Report",
        "source_url": "https://www.ntia.gov/files/ntia/publications/compendium/0225.00-0328.60_01MAR14.pdf",
        "evidence_note": "NTIA公开FLTSATCOM历史下行范围。",
        "usage_boundary": "历史系统范围，不收录当前卫星频道计划或实际任务网络。",
    },
    {
        "parameter_id": "PAR-UHF-SATCOM-UP",
        "system_or_service": "FLTSATCOM/UHF移动卫星上行参考",
        "mission_role": "战术和战略窄带卫星通信上行",
        "case_links": "CASE-OEF-2001; CASE-OIF-2003",
        "frequency_start_mhz": 292.85,
        "frequency_end_mhz": 317.325,
        "center_frequency_mhz": None,
        "channel_step_khz": None,
        "occupied_bandwidth_khz": None,
        "power_w": None,
        "channel_count": None,
        "range_km": "卫星覆盖",
        "waveform_or_access": "窄带移动卫星；具体频道和接入计划未公开",
        "mobility": "背负、车载、舰载、机载终端",
        "assignment_mode": "卫星上行频道/网络资源",
        "planning_relation": "超视距关键链路；上行发射需区域和时段授权",
        "parameter_status": "公开精确历史范围",
        "confidence": "高",
        "source_org": "NTIA",
        "source_title": "225-328.6 MHz Federal Spectrum Use Report",
        "source_url": "https://www.ntia.gov/files/ntia/publications/compendium/0225.00-0328.60_01MAR14.pdf",
        "evidence_note": "NTIA公开FLTSATCOM历史上行范围。",
        "usage_boundary": "历史系统范围，不收录当前卫星频道计划或实际任务网络。",
    },
    {
        "parameter_id": "PAR-WGS-X",
        "system_or_service": "WGS X-band业务类别",
        "mission_role": "全球高容量军事卫星通信",
        "case_links": "",
        "frequency_start_mhz": None,
        "frequency_end_mhz": None,
        "center_frequency_mhz": None,
        "channel_step_khz": None,
        "occupied_bandwidth_khz": None,
        "power_w": None,
        "channel_count": None,
        "range_km": "全球覆盖",
        "waveform_or_access": "WGS提供X-band服务；具体转发器参数未公开",
        "mobility": "固定、可搬移、地面/空中/舰载终端",
        "assignment_mode": "卫星带宽/波束资源",
        "planning_relation": "高容量骨干链路；需带宽、波束和终端能力联合规划",
        "parameter_status": "公开频段类别边界",
        "confidence": "中高",
        "source_org": "U.S. Space Force / U.S. Army",
        "source_title": "Wideband Global SATCOM Fact Sheet; D3SOE Handbook",
        "source_url": "https://www.spaceforce.mil/about-us/fact-sheets/article/2197740/wideband-global-satcom-satellite/ | https://api.army.mil/e2/c/downloads/2023/01/19/7f7281ee/18-28-operating-in-a-denied-degraded-and-disrupted-space-operational-environment-handbook-jun-18-public.pdf",
        "evidence_note": "Space Force确认WGS提供X/Ka业务；8-12 GHz来自陆军公开波段定义，不是WGS具体转发器范围。",
        "usage_boundary": "不得把整个X波段直接转成WGS可用规则。",
    },
    {
        "parameter_id": "PAR-WGS-KA",
        "system_or_service": "WGS Ka-band业务类别",
        "mission_role": "全球高容量军事卫星通信",
        "case_links": "",
        "frequency_start_mhz": None,
        "frequency_end_mhz": None,
        "center_frequency_mhz": None,
        "channel_step_khz": None,
        "occupied_bandwidth_khz": None,
        "power_w": None,
        "channel_count": None,
        "range_km": "全球覆盖",
        "waveform_or_access": "WGS提供Ka-band服务；具体转发器参数未公开",
        "mobility": "固定、可搬移、地面/空中/舰载终端",
        "assignment_mode": "卫星带宽/波束资源",
        "planning_relation": "高容量骨干和广播；需考虑雨衰及终端口径",
        "parameter_status": "公开频段类别边界",
        "confidence": "中高",
        "source_org": "U.S. Space Force / U.S. Army",
        "source_title": "Wideband Global SATCOM Fact Sheet; D3SOE Handbook",
        "source_url": "https://www.spaceforce.mil/about-us/fact-sheets/article/2197740/wideband-global-satcom-satellite/ | https://api.army.mil/e2/c/downloads/2023/01/19/7f7281ee/18-28-operating-in-a-denied-degraded-and-disrupted-space-operational-environment-handbook-jun-18-public.pdf",
        "evidence_note": "27-40 GHz是公开Ka波段定义，不是WGS具体上下行或转发器范围。",
        "usage_boundary": "不得把整个Ka波段直接转成WGS可用规则。",
    },
    {
        "parameter_id": "PAR-UAS-CNPC-5030",
        "system_or_service": "UAS CNPC公共规划参考",
        "mission_role": "非隔离空域无人机安全控制与非载荷通信",
        "case_links": "",
        "frequency_start_mhz": 5030.0,
        "frequency_end_mhz": 5091.0,
        "center_frequency_mhz": None,
        "channel_step_khz": None,
        "occupied_bandwidth_khz": None,
        "power_w": None,
        "channel_count": None,
        "range_km": "地面视距链路",
        "waveform_or_access": "高完整性CNPC；具体标准参数另行建模",
        "mobility": "无人机/远程控制中心",
        "assignment_mode": "安全控制链路",
        "planning_relation": "飞控高可靠链路，应与载荷数据分离并设置最高保障级",
        "parameter_status": "公开规划频段",
        "confidence": "高",
        "source_org": "NTIA / FAA",
        "source_title": "5030-5250 MHz Spectrum Compendium; UAS NAS Integration Roadmap",
        "source_url": "https://www.ntia.gov/files/ntia/publications/compendium/5030.00-5250.00-02092021.pdf | https://www.faa.gov/sites/faa.gov/files/uas/resources/policy_library/Second_Edition_Integration_of_Civil_UAS_NAS_Roadmap_July%25202018.pdf",
        "evidence_note": "5030-5091 MHz是CNPC公共规划频段，不是伊拉克/阿富汗战例频率。",
        "usage_boundary": "仅作未来控制链路和数据模型参考。",
    },
    {
        "parameter_id": "PAR-UAS-TELEMETRY-2200",
        "system_or_service": "航空/UAS试验遥测参考",
        "mission_role": "飞行试验遥测、高分辨率视频和无人飞行器测试",
        "case_links": "",
        "frequency_start_mhz": 2200.0,
        "frequency_end_mhz": 2290.0,
        "center_frequency_mhz": None,
        "channel_step_khz": None,
        "occupied_bandwidth_khz": None,
        "power_w": None,
        "channel_count": None,
        "range_km": None,
        "waveform_or_access": "航空遥测；高分辨率视频需求",
        "mobility": "试验航空器/UAS与地面站",
        "assignment_mode": "遥测频道/连续带宽",
        "planning_relation": "试验任务时段化占用；需与空间业务协调",
        "parameter_status": "公开业务频段",
        "confidence": "高",
        "source_org": "NTIA",
        "source_title": "2200-2290 MHz Federal Spectrum Use Report",
        "source_url": "https://www.ntia.gov/files/ntia/publications/compendium/2200.00-2290.00_01MAY15.pdf",
        "evidence_note": "NTIA明确DoD和商业飞行试验、高分辨率视频及无人飞行器测试需求。",
        "usage_boundary": "试验遥测频段，不代表作战UAS实际控制或载荷链路。",
    },
    {
        "parameter_id": "PAR-PRC158",
        "system_or_service": "AN/PRC-158双通道单兵背负电台",
        "mission_role": "战术语音、数据、视距/超视距和跨频段冗余通信",
        "case_links": "",
        "frequency_start_mhz": None,
        "frequency_end_mhz": None,
        "center_frequency_mhz": None,
        "channel_step_khz": None,
        "occupied_bandwidth_khz": "5/25（仅UHF SATCOM频道类别）",
        "power_w": "窄带最高10；SATCOM/宽带最高20",
        "channel_count": 2,
        "range_km": None,
        "waveform_or_access": "SINCGARS、SATURN、MUOS、SATCOM、WREN TSM等公开兼容类别",
        "mobility": "背负/车载扩展",
        "assignment_mode": "双通道并发；窄带、宽带和卫星链路按任务选择",
        "planning_relation": "主备链路并发、跨频段中继和语音/数据差异化保障",
        "parameter_status": "公开能力与功率上限；数值频率未公开",
        "confidence": "高",
        "source_org": "U.S. Army",
        "source_title": "ATP 6-02.53 Techniques for Tactical Radio Operations; Handheld, Manpack and Small Form Fit",
        "source_url": "https://rdl.train.army.mil/catalog-ws/view/100.ATSC/0C45D378-25E0-438E-8881-749EF51DE080-1452191121290/atp6_02x53.pdf | https://peoc3n.army.mil/Organizations/PM-Tactical-Radios/Handheld-Manpack-and-Small-Form-Fit/",
        "evidence_note": "陆军资料公开双通道、兼容波形和不同业务的最高功率；调谐起止频率保持为空。",
        "usage_boundary": "不收录密钥容量、网络预置、跳频参数或任务频道。",
    },
    {
        "parameter_id": "PAR-MUOS-BAND-A",
        "system_or_service": "MUOS公开系统频段A",
        "mission_role": "全球移动窄带卫星语音、数据和视频",
        "case_links": "",
        "frequency_start_mhz": 243.525,
        "frequency_end_mhz": 270.05,
        "center_frequency_mhz": None,
        "channel_step_khz": None,
        "occupied_bandwidth_khz": None,
        "power_w": None,
        "channel_count": None,
        "range_km": "全球覆盖",
        "waveform_or_access": "WCDMA与传统UHF兼容载荷",
        "mobility": "手持、背负、车载、舰载和机载终端",
        "assignment_mode": "卫星接入、优先级和容量资源",
        "planning_relation": "移动超视距链路；与传统UHF用户并存",
        "parameter_status": "公开系统使用范围",
        "confidence": "高",
        "source_org": "NTIA / GAO",
        "source_title": "225-328.6 MHz Federal Spectrum Use Report; GAO-21-105283",
        "source_url": "https://www.ntia.gov/files/ntia/publications/compendium/0225.00-0328.60_21NOV14.pdf | https://www.gao.gov/products/gao-21-105283",
        "evidence_note": "NTIA公开MUOS使用两个不连续频段；本记录只保存其中一段，不推定上下行方向或频道计划。",
        "usage_boundary": "系统使用范围不等于当前可用容量、波束资源或行动频道。",
    },
    {
        "parameter_id": "PAR-MUOS-BAND-B",
        "system_or_service": "MUOS公开系统频段B",
        "mission_role": "全球移动窄带卫星语音、数据和视频",
        "case_links": "",
        "frequency_start_mhz": 280.0,
        "frequency_end_mhz": 320.0,
        "center_frequency_mhz": None,
        "channel_step_khz": None,
        "occupied_bandwidth_khz": None,
        "power_w": None,
        "channel_count": None,
        "range_km": "全球覆盖",
        "waveform_or_access": "WCDMA与传统UHF兼容载荷；GAO称容量可较传统系统提高约10倍",
        "mobility": "手持、背负、车载、舰载和机载终端",
        "assignment_mode": "卫星接入、优先级和容量资源",
        "planning_relation": "移动超视距链路；与传统UHF用户并存",
        "parameter_status": "公开系统使用范围",
        "confidence": "高",
        "source_org": "NTIA / GAO",
        "source_title": "225-328.6 MHz Federal Spectrum Use Report; GAO-21-105283",
        "source_url": "https://www.ntia.gov/files/ntia/publications/compendium/0225.00-0328.60_21NOV14.pdf | https://www.gao.gov/products/gao-21-105283",
        "evidence_note": "两个不连续频段必须分条存储；10倍为GAO公开容量描述，不是单用户保证速率。",
        "usage_boundary": "不得把243.525-320 MHz合并为连续MUOS可用频段。",
    },
    {
        "parameter_id": "PAR-RADAR-TPQ50",
        "system_or_service": "AN/TPQ-50轻型反迫击炮/多任务雷达",
        "mission_role": "近程火箭、火炮、迫击炮定位和低慢小目标辅助探测",
        "case_links": "",
        "frequency_start_mhz": None,
        "frequency_end_mhz": None,
        "center_frequency_mhz": None,
        "channel_step_khz": None,
        "occupied_bandwidth_khz": None,
        "power_w": None,
        "channel_count": None,
        "range_km": "0.5-10（条令定位范围）；最高约15取决于目标和轨迹（ODIN）",
        "waveform_or_access": "L波段类别；360度电子扫描；具体调谐和脉冲参数未公开",
        "mobility": "三脚架或车载；两人快速架设",
        "assignment_mode": "雷达时段、覆盖区和任务模式",
        "planning_relation": "近程防护、C-RAM/FAAD C2接入和雷达共址兼容",
        "parameter_status": "仅公开频段类别和能力范围",
        "confidence": "高",
        "source_org": "U.S. Army ODIN / Army Budget",
        "source_title": "AN/TPQ-50 American Counterfire Radar System; PB 2023 Firefinder Justification",
        "source_url": "https://odin.t2com.army.mil/WEG/Asset/c57802f406c1c9733314e686c6be00ea | https://www.asafm.army.mil/Portals/72/Documents/BudgetMaterial/2023/Base%20Budget/rdte/vol_2-Budget_Activity_5C.pdf",
        "evidence_note": "陆军预算资料明确该系统支援OIR/OFS；ODIN的1200 W为供电需求，因此射频功率保持为空。",
        "usage_boundary": "不把通用L波段边界写入数值字段，也不推定具体作战部署。",
    },
    {
        "parameter_id": "PAR-RADAR-KURFS",
        "system_or_service": "Ku-band Radio Frequency System (KuRFS)",
        "mission_role": "反无人机空域监视、目标跟踪和效应器引导",
        "case_links": "",
        "frequency_start_mhz": None,
        "frequency_end_mhz": None,
        "center_frequency_mhz": None,
        "channel_step_khz": None,
        "occupied_bandwidth_khz": None,
        "power_w": None,
        "channel_count": None,
        "range_km": None,
        "waveform_or_access": "Ku波段、360度；具体工作范围和波形未公开",
        "mobility": "固定、半固定或车载集成",
        "assignment_mode": "持续/按需空域监视与目标跟踪",
        "planning_relation": "与AN/TPQ-50、光电、FAAD C2和多种效应器联合编组",
        "parameter_status": "仅公开频段类别和系统关系",
        "confidence": "高",
        "source_org": "U.S. Army",
        "source_title": "Advancing the U.S. Army's Counter-UAS Mission Command Systems",
        "source_url": "https://www.armyupress.army.mil/Journals/Military-Review/English-Edition-Archives/May-June-2024/MJ-24-Modern-Warfare/",
        "evidence_note": "公开资料支持Ku波段、360度和C-UAS系统关系，不支持填写通用Ku波段数值边界。",
        "usage_boundary": "不收录探测门限、跟踪精度、效应器控制参数或实战部署。",
    },
    {
        "parameter_id": "PAR-RADAR-SPY6",
        "system_or_service": "AN/SPY-6(V)1 Air and Missile Defense Radar",
        "mission_role": "舰载一体化防空反导、监视、跟踪和目标判别",
        "case_links": "",
        "frequency_start_mhz": None,
        "frequency_end_mhz": None,
        "center_frequency_mhz": None,
        "channel_step_khz": None,
        "occupied_bandwidth_khz": None,
        "power_w": None,
        "channel_count": None,
        "range_km": None,
        "waveform_or_access": "S波段有源阵列类别；具体调谐、波形和功率未公开",
        "mobility": "DDG 51 Flight III舰载固定阵列",
        "assignment_mode": "多任务雷达时间与阵面资源",
        "planning_relation": "同时支持防空反导及水面任务，需要与舰载通信、数据链和其他雷达兼容",
        "parameter_status": "仅公开频段类别和相对能力",
        "confidence": "高",
        "source_org": "U.S. Navy",
        "source_title": "Air and Missile Defense Radar Fact File; FY 2018 Navy SCN Budget",
        "source_url": "https://www.navy.mil/Resources/Fact-Files/Display-FactFiles/Article/2166758/air-and-missile-defense-radar-amdr/ | https://www.secnav.navy.mil/fmc/fmb/Documents/18pres/SCN_Book.pdf",
        "evidence_note": "海军公开V1为四阵面、每阵37个RMA并提供相对SPY+16 dB灵敏度；该值不是绝对接收门限。",
        "usage_boundary": "不将SPY-6与特定红海参战舰艇绑定，不填具体雷达模式和火控数据。",
    },
    {
        "parameter_id": "PAR-HYBRID-SATCOM",
        "system_or_service": "DoD混合卫星通信架构参考",
        "mission_role": "在受威胁和容量变化条件下提供多路径卫星通信",
        "case_links": "",
        "frequency_start_mhz": None,
        "frequency_end_mhz": None,
        "center_frequency_mhz": None,
        "channel_step_khz": None,
        "occupied_bandwidth_khz": None,
        "power_w": None,
        "channel_count": None,
        "range_km": "全球/区域，依组成系统",
        "waveform_or_access": "军用与商业、多轨道和多类终端组合；具体频段依资源提供者",
        "mobility": "固定与移动用户终端",
        "assignment_mode": "终端、地面站、卫星、波束和网络路径联合选择",
        "planning_relation": "把SATCOM从单一频点分配提升为多路径容量和可恢复性规划",
        "parameter_status": "公开架构类别；无统一频率范围",
        "confidence": "高",
        "source_org": "GAO",
        "source_title": "GAO-25-107034 DOD Satellite Communications",
        "source_url": "https://files.gao.gov/reports/GAO-25-107034/index.html",
        "evidence_note": "GAO说明混合SATCOM需同步用户终端、地面站、卫星系统、网络和用户；本记录不虚构统一频段。",
        "usage_boundary": "只用于资源编排数据模型，不代表任何商业或军用容量已获授权。",
    },
    {
        "parameter_id": "PAR-PRC160",
        "system_or_service": "AN/PRC-160宽带HF电台",
        "mission_role": "卫星通信不可用或受限时的超视距战术语音和数据通信",
        "case_links": "",
        "frequency_start_mhz": 1.6,
        "frequency_end_mhz": 60.0,
        "center_frequency_mhz": None,
        "channel_step_khz": None,
        "occupied_bandwidth_khz": None,
        "power_w": None,
        "channel_count": None,
        "range_km": "依传播、天线、时段和电离层条件",
        "waveform_or_access": "宽带HF软件定义无线电；公开最高数据率120 kbit/s",
        "mobility": "背负、车载或固定节点",
        "assignment_mode": "HF链路、时间窗和传播条件联合规划",
        "planning_relation": "作为SATCOM和视距网络的超视距备用链路；适用于PACE和受限发射状态",
        "parameter_status": "公开设备范围和最高数据率",
        "confidence": "中高",
        "source_org": "U.S. Army",
        "source_title": "Adapting to Multi-Domain Battlefield; Helicopter and Multi-Mission Radios",
        "source_url": "https://www.lineofdeparture.army.mil/Journals/Armor/Armor-Archive/Spring-2025-Edition/Adapting-to-the-Multi-Domain-Battlefield/ | https://peoc3n.army.mil/Organizations/PM-Tactical-Radios/Helicopter-and-Multi-Mission-Radios/",
        "evidence_note": "陆军公开表给出1.6-60 MHz；项目办公室给出最高120 kbit/s。速率是能力上限，不是任意传播条件下的保证值。",
        "usage_boundary": "不收录自动链路建立参数、天线配置、传播预测结果或任务频点。",
    },
]


PARAMETER_METADATA = {
    "PAR-SINCGARS": ("equipment_range", "SRC-01", "海湾战争地面战斗网装备基线"),
    "PAR-MIL-AIR-VOICE": ("service_plan", "SRC-11", "军用航空话音业务规划参考"),
    "PAR-EPLRS": ("system_band", "SRC-08", "战术位置报告与数据分发系统基线"),
    "PAR-LINK16": ("system_band", "SRC-09; SRC-10", "联合战术数据链系统基线"),
    "PAR-GPS-L5": ("protected_center", "SRC-09", "PNT敏感接收业务保护对象"),
    "PAR-GPS-L2": ("protected_center", "SRC-09", "PNT敏感接收业务保护对象"),
    "PAR-GPS-L1": ("protected_center", "SRC-09", "PNT敏感接收业务保护对象"),
    "PAR-UAS-C-KU": ("category_only", "SRC-05", "伊拉克/阿富汗无人系统公开类别"),
    "PAR-TRR-4400": ("coexistence_study_band", "SRC-23", "频谱迁移与共存评估参考"),
    "PAR-RADAR-TPQ53": ("equipment_range", "SRC-13", "伊拉克/阿富汗时期后段反炮兵雷达能力参考"),
    "PAR-RADAR-SENTINEL": ("category_only", "SRC-14; SRC-24", "后伊拉克战争时期防空雷达能力参考"),
    "PAR-RADAR-SURVEILLANCE-2700": ("service_allocation", "SRC-15", "通用雷达共存基线"),
    "PAR-RADAR-MARITIME-2900": ("service_allocation", "SRC-16", "通用海上雷达共存基线"),
    "PAR-UHF-SATCOM-DOWN": ("historical_system_range", "SRC-17", "OEF/OIF超视距通信需求背景"),
    "PAR-UHF-SATCOM-UP": ("historical_system_range", "SRC-17", "OEF/OIF超视距通信需求背景"),
    "PAR-WGS-X": ("category_only", "SRC-18; SRC-19", "后OEF/OIF宽带卫星通信能力参考"),
    "PAR-WGS-KA": ("category_only", "SRC-18; SRC-19", "后OEF/OIF宽带卫星通信能力参考"),
    "PAR-UAS-CNPC-5030": ("planned_service_allocation", "SRC-20; SRC-22", "未来无人机安全控制链路参考"),
    "PAR-UAS-TELEMETRY-2200": ("service_allocation", "SRC-21", "无人机试验与鉴定业务参考"),
    "PAR-PRC158": ("category_only", "SRC-34; SRC-35", "现代双通道战术无线电能力参考"),
    "PAR-MUOS-BAND-A": ("system_band", "SRC-36; SRC-37", "现代移动窄带卫星通信系统参考"),
    "PAR-MUOS-BAND-B": ("system_band", "SRC-36; SRC-37", "现代移动窄带卫星通信系统参考"),
    "PAR-RADAR-TPQ50": ("category_only", "SRC-38; SRC-39", "OIR/OFS近程反炮兵和基地防护能力参考"),
    "PAR-RADAR-KURFS": ("category_only", "SRC-40", "现代分层反无人机探测能力参考"),
    "PAR-RADAR-SPY6": ("category_only", "SRC-41; SRC-42", "现代舰载一体化防空反导能力参考"),
    "PAR-HYBRID-SATCOM": ("category_only", "SRC-43", "受威胁环境下的多路径卫星通信架构参考"),
    "PAR-PRC160": ("equipment_range", "SRC-45; SRC-46", "现代HF超视距和PACE通信能力参考"),
}

for parameter in PUBLIC_PARAMETERS:
    frequency_scope, source_ids, baseline_context = PARAMETER_METADATA[parameter["parameter_id"]]
    parameter["frequency_scope"] = frequency_scope
    parameter["source_ids"] = source_ids
    parameter["baseline_context"] = baseline_context


FIELD_DICTIONARY = [
    ("case_id / parameter_id", "稳定记录编号", "用于来源追踪和后续增量更新"),
    ("case_type", "战例类型", "combat_operation / noncombatant_evacuation / cross_operation_case / joint_experiment"),
    ("operation / case_links", "战例及关联", "参数关联到需求背景，不代表战例实际使用了系统全部调谐范围"),
    ("phase_model", "公开事实提炼的任务阶段", "用于生成任务时段骨架；不是历史行动时间表"),
    ("dynamic_events", "可用于重筹的事件类别", "只描述公开现象或合成注入，不保存真实任务数据"),
    ("frequency_start_mhz / frequency_end_mhz", "公开数值范围", "仅在来源明确给出时填写；必须结合frequency_scope解释"),
    ("center_frequency_mhz", "公开中心频率", "适用于GPS等保护对象"),
    ("channel_step_khz", "频道间隔或规划步进", "来源未明确时留空；不得用设备带宽替代"),
    ("occupied_bandwidth_khz", "单项占用带宽", "来源未明确时留空"),
    ("power_w", "公开功率或范围", "型号差异明显或未公开时留空"),
    ("frequency_scope", "频率数值语义", "equipment_range / system_band / service_allocation / service_plan / protected_center / category_only / historical_system_range / planned_service_allocation / coexistence_study_band"),
    ("parameter_status", "披露粒度", "公开精确范围 / 公开业务规划范围 / 仅公开频段类别"),
    ("source_ids", "来源目录编号", "战例和参数均使用一个或多个SRC-*编号；必须能在来源目录中解析"),
    ("baseline_context", "参考背景", "用于保存非战例外键的时代、能力或共存背景"),
    ("usage_boundary", "使用边界", "防止把工作范围误当授权或实际行动频道"),
    ("confidence", "证据置信度", "高=政府原始资料直接支持；中=政府资料中的评估或汇总"),
]


SOURCES = [
    ("SRC-01", "U.S. Army", "1992 Weapon Systems Handbook", "SINCGARS参数与西南亚表现", "https://asc.army.mil/docs/wsh2/1992-wsh.pdf", "政府原始资料"),
    ("SRC-02", "GAO", "Operation Desert Storm: Apache Helicopter Fratricide Incident", "海湾战争航空无线电类别", "https://www.gao.gov/assets/osi-93-4.pdf", "政府调查"),
    ("SRC-03", "GAO", "GAO-01-401 Kosovo Air Operations", "Task Force Hawk联合互操作问题", "https://www.gao.gov/products/gao-01-401", "政府审计"),
    ("SRC-04", "GAO", "GAO-04-547 Military Operations", "Kosovo/Afghanistan/Iraq网络化作战与互操作", "https://www.gao.gov/products/gao-04-547", "政府审计"),
    ("SRC-05", "GAO", "GAO-06-49 Unmanned Aircraft Systems", "UAS C/Ku频段类别、拥塞和任务延迟", "https://www.gao.gov/products/gao-06-49", "政府审计"),
    ("SRC-06", "GAO", "GAO-07-836 Unmanned Aircraft Systems", "Iraq/Afghanistan UAS带宽和协调问题", "https://www.gao.gov/products/gao-07-836", "政府审计"),
    ("SRC-07", "U.S. Army", "WIN-T: It is real, it is here and it works", "OEF/OIF超视距网络需求", "https://www.army.mil/article/25076/warfighter_information_network_tactical_its_real_its_here_and_it_works", "军方官方文章"),
    ("SRC-08", "NTIA", "420-450 MHz Federal Spectrum Use Report", "EPLRS/AEPLRS与频段用途", "https://www.ntia.gov/files/ntia/publications/compendium/0420.00-0450.00_01MAY15.pdf", "政府频谱报告"),
    ("SRC-09", "NTIA", "1164-1215 MHz Federal Spectrum Use Report", "Link 16授权范围和GPS中心频率", "https://www.ntia.gov/files/ntia/publications/compendium/1164.00-1215.00_01MAR14.pdf", "政府频谱报告"),
    ("SRC-10", "U.S. Army", "FM 3-01 Air and Missile Defense Operations", "Link 16离散频率数和公开速率", "https://rdl.train.army.mil/catalog-ws/view/100.ATSC/C01CC9C1-DA1C-4D5E-A6EB-5FCFAE218DCD-1398170439966/fm3_01.pdf", "公开条令"),
    ("SRC-11", "U.S. DOT / NTIA", "Transportation Strategic Spectrum Plan", "军用航空空地业务规划参数", "https://www.ntia.gov/sites/default/files/publications/transportation_strategic_spectrum_plan_nov2007_0.pdf", "政府规划资料"),
    ("SRC-12", "GAO", "GAO-26-107873 Spectrum Management", "频率申请数据包含地点、时间、频段和持续时长", "https://files.gao.gov/reports/GAO-26-107873/index.html", "政府审计"),
    ("SRC-13", "U.S. Army ODIN", "AN/TPQ-53 Counterfire Radar", "Q-53 S波段和公开覆盖距离", "https://odin.t2com.army.mil/WEG/Asset/6ea3c7edc1d7b3bab022f375761f3ee6", "军方公开数据库"),
    ("SRC-14", "U.S. Army Acquisition", "Program Portfolio 2024", "Sentinel项目与X波段能力背景", "https://api.army.mil/e2/c/downloads/2024/07/19/ab2038a9/u-s-army-portfolio-2024.pdf", "军方项目资料"),
    ("SRC-15", "NTIA", "2700-2900 MHz Federal Spectrum Use Report", "监视雷达和频率协调", "https://www.ntia.gov/files/ntia/publications/compendium/2700.00-2900.00_01MAR14.pdf", "政府频谱报告"),
    ("SRC-16", "NTIA", "2900-3100 MHz Federal Spectrum Use Report", "海上和军用雷达用途", "https://www.ntia.gov/files/ntia/publications/compendium/2900.00-3100.00_01MAY15.pdf", "政府频谱报告"),
    ("SRC-17", "NTIA", "225-328.6 MHz Federal Spectrum Use Report", "FLTSATCOM历史上下行范围", "https://www.ntia.gov/files/ntia/publications/compendium/0225.00-0328.60_01MAR14.pdf", "政府频谱报告"),
    ("SRC-18", "U.S. Space Force", "Wideband Global SATCOM Fact Sheet", "WGS X/Ka波段业务", "https://www.spaceforce.mil/about-us/fact-sheets/article/2197740/wideband-global-satcom-satellite/", "军方事实页"),
    ("SRC-19", "U.S. Army", "D3SOE Handbook", "公开通信波段边界与典型系统", "https://api.army.mil/e2/c/downloads/2023/01/19/7f7281ee/18-28-operating-in-a-denied-degraded-and-disrupted-space-operational-environment-handbook-jun-18-public.pdf", "公开手册"),
    ("SRC-20", "NTIA / FAA", "5030-5250 MHz Spectrum Compendium", "UAS CNPC 5030-5091 MHz", "https://www.ntia.gov/files/ntia/publications/compendium/5030.00-5250.00-02092021.pdf", "政府频谱报告"),
    ("SRC-21", "NTIA", "2200-2290 MHz Federal Spectrum Use Report", "航空/UAS试验遥测", "https://www.ntia.gov/files/ntia/publications/compendium/2200.00-2290.00_01MAY15.pdf", "政府频谱报告"),
    ("SRC-22", "FAA", "Integration of Civil UAS in the National Airspace System Roadmap", "UAS CNPC安全关键用途与5030-5091 MHz规划", "https://www.faa.gov/sites/faa.gov/files/uas/resources/policy_library/Second_Edition_Integration_of_Civil_UAS_NAS_Roadmap_July%25202018.pdf", "政府路线图"),
    ("SRC-23", "U.S. Department of Defense / NTIA", "DoD 4400-4940 MHz Band Assessment", "战术中继与其他系统的迁移和共存评估", "https://www.ntia.gov/sites/default/files/publications/dodassessment_0.pdf", "政府频谱评估"),
    ("SRC-24", "U.S. Army Acquisition Support Center", "Acquisition partnership to roll out new improved Sentinel Radar", "AN/MPQ-64A3三维X波段、360度和75 km", "https://asc.army.mil/web/access-acquisition-partnership-to-roll-out-new-improved-sentinel-radar/", "军方采办文章"),
    ("SRC-25", "U.S. Army TRADOC", "Mosul Study Group: What the Battle for Mosul Teaches the Force", "摩苏尔频谱环境、UAS/C-UAS和友军兼容问题", "https://api.army.mil/e2/c/downloads/2023/01/19/e9325e8b/17-24u-mosul-study-group-what-the-battle-for-mosul-teaches-the-force-sep-17-public.pdf", "军方战例研究"),
    ("SRC-26", "U.S. Air Force", "Compass Call dominates OIR with electronic warfare", "OIR通信对抗任务和跨域协同", "https://www.af.mil/News/Features/Article/1295655/compass-call-dominates-oir-with-electronic-warfare/", "军方官方文章"),
    ("SRC-27", "GAO", "GAO-21-64 Electromagnetic Spectrum Operations", "叙利亚受干扰通信环境和DoD频谱治理", "https://www.gao.gov/assets/gao-21-64.pdf", "政府审计"),
    ("SRC-28", "U.S. Department of Defense / USTRANSCOM", "Transportation Command Aids in Historic Evacuation", "喀布尔撤离规模、节奏和跨洲空运", "https://www.defense.gov/News/News-Stories/Article/Article/2764916/transportation-command-aids-in-historic-evacuation/", "军方行动回顾"),
    ("SRC-29", "U.S. Department of State / Department of Defense", "Joint Statement on Afghanistan", "机场夺控、兵力规模和空中交通管制任务", "https://www.defense.gov/News/Releases/Release/Article/2732053/joint-statement-from-the-department-of-state-and-department-of-defense-update-o/", "政府联合声明"),
    ("SRC-30", "U.S. Department of Defense / NAVCENT", "Press Briefing on Operation Prosperity Guardian", "红海护航、商船双向通信和多国协同", "https://www.defense.gov/News/Transcripts/Transcript/Article/3631484/navcent-commander-vice-admiral-brad-cooper-holds-an-off-camera-on-the-record-pr/", "军方行动发布会"),
    ("SRC-31", "U.S. Department of Defense / U.S. Navy", "Navy's Top Officer Credits Training and Logistics With Meeting Red Sea Mission", "红海持续防空任务和保障需求", "https://www.defense.gov/News/News-Stories/Article/Article/3723681/navys-top-officer-credits-training-logistics-with-meeting-red-sea-mission/", "军方行动回顾"),
    ("SRC-32", "U.S. Navy", "USS Carney: a Destroyer at War", "红海10小时多目标防御战例", "https://www.navy.mil/Press-Office/News-Stories/display-news/Article/3984206/uss-carney-a-destroyer-at-war/", "军方行动回顾"),
    ("SRC-33", "U.S. Department of Defense / U.S. Army", "Network Capability Provides Successful Start to Project Convergence Capstone 4", "联合多国混合网络、受限环境和CJADC2实验", "https://www.defense.gov/News/News-Stories/Article/Article/3692858/network-capability-provides-successful-start-to-project-convergence-capstone-4/", "军方实验报道"),
    ("SRC-34", "U.S. Army CPE C2IN", "Handheld, Manpack and Small Form Fit", "AN/PRC-158双通道和公开波形类别", "https://peoc3n.army.mil/Organizations/PM-Tactical-Radios/Handheld-Manpack-and-Small-Form-Fit/", "军方项目资料"),
    ("SRC-35", "U.S. Army", "ATP 6-02.53 Techniques for Tactical Radio Operations", "AN/PRC-158公开功率和UHF SATCOM频道类别", "https://rdl.train.army.mil/catalog-ws/view/100.ATSC/0C45D378-25E0-438E-8881-749EF51DE080-1452191121290/atp6_02x53.pdf", "公开条令"),
    ("SRC-36", "NTIA", "225-328.6 MHz Federal Spectrum Use Report", "MUOS两个不连续系统频段和WCDMA", "https://www.ntia.gov/files/ntia/publications/compendium/0225.00-0328.60_21NOV14.pdf", "政府频谱报告"),
    ("SRC-37", "GAO", "GAO-21-105283 Satellite Communications", "MUOS容量、终端部署和旧系统超订问题", "https://www.gao.gov/products/gao-21-105283", "政府审计"),
    ("SRC-38", "U.S. Army ODIN", "AN/TPQ-50 American Counterfire Radar System", "L波段类别、覆盖范围和360度能力", "https://odin.t2com.army.mil/WEG/Asset/c57802f406c1c9733314e686c6be00ea", "军方公开数据库"),
    ("SRC-39", "U.S. Army", "PB 2023 Firefinder RDT&E Justification", "AN/TPQ-50任务、0.5-10 km和OIR/OFS支援", "https://www.asafm.army.mil/Portals/72/Documents/BudgetMaterial/2023/Base%20Budget/rdte/vol_2-Budget_Activity_5C.pdf", "军方预算资料"),
    ("SRC-40", "U.S. Army Military Review", "Advancing the U.S. Army's Counter-UAS Mission Command Systems", "KuRFS频段类别、360度和C-UAS系统关系", "https://www.armyupress.army.mil/Journals/Military-Review/English-Edition-Archives/May-June-2024/MJ-24-Modern-Warfare/", "军方专业期刊"),
    ("SRC-41", "U.S. Navy", "Air and Missile Defense Radar Fact File", "AN/SPY-6阵面、RMA数量和相对灵敏度", "https://www.navy.mil/Resources/Fact-Files/Display-FactFiles/Article/2166758/air-and-missile-defense-radar-amdr/", "军方事实页"),
    ("SRC-42", "U.S. Navy", "FY 2018 Shipbuilding and Conversion Budget", "AN/SPY-6 S波段类别和系统组成", "https://www.secnav.navy.mil/fmc/fmb/Documents/18pres/SCN_Book.pdf", "军方预算资料"),
    ("SRC-43", "GAO", "GAO-25-107034 DOD Satellite Communications", "混合SATCOM架构、终端、地面站和网络同步", "https://files.gao.gov/reports/GAO-25-107034/index.html", "政府审计"),
    ("SRC-44", "U.S. Army Military Review", "C-UAS Operations", "2023-2024 OIR基地防护、多传感器融合和人员约束", "https://www.armyupress.army.mil/Portals/7/military-review/Archives/English/JA-24/C-UAS%20Operations/C-UAS-Operations-UA.pdf", "军方战例复盘"),
    ("SRC-45", "U.S. Army Armor", "Adapting to Multi-Domain Battlefield: Developing Emissions Control SOP", "AN/PRC-160公开调谐范围和EMCON筹划背景", "https://www.lineofdeparture.army.mil/Journals/Armor/Armor-Archive/Spring-2025-Edition/Adapting-to-the-Multi-Domain-Battlefield/", "军方专业期刊"),
    ("SRC-46", "U.S. Army CPE C2IN", "Helicopter and Multi-Mission Radios", "AN/PRC-160超视距定位和最高120 kbit/s", "https://peoc3n.army.mil/Organizations/PM-Tactical-Radios/Helicopter-and-Multi-Mission-Radios/", "军方项目资料"),
]


def style_sheet(sheet, table_name=None):
    thin = Side(style="thin", color="C7D2E2")
    sheet.freeze_panes = "A2"
    sheet.auto_filter.ref = sheet.dimensions
    sheet.row_dimensions[1].height = 28
    for cell in sheet[1]:
        cell.font = Font(name="Arial", size=10, bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor="17365D")
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cell.border = Border(bottom=thin)
    for row in sheet.iter_rows(min_row=2):
        for cell in row:
            cell.font = Font(name="Arial", size=9, color="1F2937")
            cell.alignment = Alignment(vertical="top", wrap_text=True)
            cell.border = Border(bottom=thin)
        if row[0].row % 2 == 0:
            for cell in row:
                cell.fill = PatternFill("solid", fgColor="F6F8FB")
    for column_index, column in enumerate(sheet.columns, start=1):
        header = str(sheet.cell(1, column_index).value or "")
        values = [str(cell.value or "") for cell in list(column)[:80]]
        width = min(55, max(12, max((len(value) for value in values), default=10) + 2))
        if "url" in header.lower():
            width = 48
        elif header in {"observed_issue_or_result", "planning_requirements", "evidence_note", "usage_boundary", "source_title"}:
            width = 42
        elif header in {"spectrum_dependent_tasks", "public_systems", "waveform_or_access"}:
            width = 32
        sheet.column_dimensions[get_column_letter(column_index)].width = width
    if table_name and sheet.max_row >= 2:
        table = Table(displayName=table_name, ref=sheet.dimensions)
        table.tableStyleInfo = TableStyleInfo(name="TableStyleMedium2", showRowStripes=True)
        sheet.add_table(table)


def add_sheet(workbook, name, rows, headers=None, table_name=None):
    sheet = workbook.create_sheet(name)
    if headers is None:
        headers = list(rows[0].keys()) if rows else []
        data_rows = [[row.get(header) for header in headers] for row in rows]
    else:
        data_rows = rows
    sheet.append(headers)
    for row in data_rows:
        sheet.append(row)
    style_sheet(sheet, table_name)
    return sheet


def validate_records():
    case_ids = {record["case_id"] for record in BATTLE_CASES}
    parameter_ids = {record["parameter_id"] for record in PUBLIC_PARAMETERS}
    source_by_id = {record[0]: record[4] for record in SOURCES}
    allowed_scopes = {
        "equipment_range",
        "system_band",
        "service_allocation",
        "service_plan",
        "protected_center",
        "category_only",
        "historical_system_range",
        "planned_service_allocation",
        "coexistence_study_band",
    }

    assert len(case_ids) == len(BATTLE_CASES), "Duplicate case_id"
    assert len(parameter_ids) == len(PUBLIC_PARAMETERS), "Duplicate parameter_id"
    assert len(source_by_id) == len(SOURCES), "Duplicate source_id"
    assert case_ids == set(CASE_METADATA), "Case metadata coverage mismatch"
    assert parameter_ids == set(PARAMETER_METADATA), "Parameter metadata coverage mismatch"

    allowed_case_types = {"combat_operation", "noncombatant_evacuation", "cross_operation_case", "joint_experiment"}
    for battle_case in BATTLE_CASES:
        assert battle_case["case_type"] in allowed_case_types, f"Unknown case type: {battle_case['case_id']}"
        linked_sources = {value.strip() for value in battle_case["source_ids"].split(";") if value.strip()}
        assert linked_sources and linked_sources <= set(source_by_id), f"Unknown case source: {battle_case['case_id']}"
        for source_id in linked_sources:
            assert source_by_id[source_id] in battle_case["source_url"], (
                f"Case source URL mismatch: {battle_case['case_id']} -> {source_id}"
            )

    for parameter in PUBLIC_PARAMETERS:
        linked_cases = {value.strip() for value in parameter["case_links"].split(";") if value.strip()}
        assert linked_cases <= case_ids, f"Unknown case link: {parameter['parameter_id']}"
        assert parameter["frequency_scope"] in allowed_scopes, f"Unknown frequency scope: {parameter['parameter_id']}"
        if parameter["frequency_scope"] == "category_only":
            assert parameter["frequency_start_mhz"] is None and parameter["frequency_end_mhz"] is None, (
                f"Category-only record has numeric range: {parameter['parameter_id']}"
            )
        linked_sources = {value.strip() for value in parameter["source_ids"].split(";") if value.strip()}
        assert linked_sources and linked_sources <= set(source_by_id), f"Unknown source link: {parameter['parameter_id']}"
        for source_id in linked_sources:
            assert source_by_id[source_id] in parameter["source_url"], (
                f"Source URL mismatch: {parameter['parameter_id']} -> {source_id}"
            )


def build_workbook(output=OUTPUT):
    validate_records()
    workbook = Workbook()
    workbook.remove(workbook.active)

    boundary = workbook.create_sheet("数据边界")
    notes = [
        ("项目", "美军公开战例与用频参数基线（第一至三批）"),
        ("更新日期", "2026-07-10"),
        ("用途", "需求建模、算法测试、仿真样例设计"),
        ("禁止解释", "系统调谐范围不等于战例实际频道；公开频段不等于本项目获得使用授权"),
        ("不收录", "具体频道、呼号、密钥、跳频表、网络初始化数据和部署坐标"),
        ("缺失处理", "来源没有公开的精确频率、功率、带宽保持为空，不用推测值补齐"),
        ("平台导入", "本工作簿不是spectrum_rules导入模板；应另行构造SIM-*仿真规则并标明假设"),
        ("证据优先级", "政府/军方原始资料 > 政府审计 > 政府汇总；不以商业宣传页作为首要证据"),
    ]
    for row in notes:
        boundary.append(row)
    boundary.column_dimensions["A"].width = 18
    boundary.column_dimensions["B"].width = 110
    for row in boundary.iter_rows():
        row[0].font = Font(name="Arial", size=10, bold=True, color="FFFFFF")
        row[0].fill = PatternFill("solid", fgColor="17365D")
        row[1].font = Font(name="Arial", size=10)
        row[0].alignment = row[1].alignment = Alignment(vertical="top", wrap_text=True)
        row[0].border = row[1].border = Border(bottom=Side(style="thin", color="C7D2E2"))
        boundary.row_dimensions[row[0].row].height = 34

    add_sheet(workbook, "战例基线", BATTLE_CASES, table_name="BattleCases")
    add_sheet(workbook, "公开用频参数", PUBLIC_PARAMETERS, table_name="SpectrumParameters")
    add_sheet(workbook, "字段字典", FIELD_DICTIONARY, headers=["字段", "含义", "使用规则"], table_name="FieldDictionary")
    add_sheet(
        workbook,
        "来源目录",
        SOURCES,
        headers=["source_id", "source_org", "source_title", "evidence_scope", "source_url", "source_type"],
        table_name="SourceCatalog",
    )

    for sheet in workbook.worksheets:
        sheet.sheet_view.showGridLines = False

    output.parent.mkdir(parents=True, exist_ok=True)
    workbook.save(output)

    check = load_workbook(output, read_only=False, data_only=False)
    assert check.sheetnames == ["数据边界", "战例基线", "公开用频参数", "字段字典", "来源目录"]
    assert check["战例基线"].max_row == len(BATTLE_CASES) + 1
    assert check["公开用频参数"].max_row == len(PUBLIC_PARAMETERS) + 1
    assert check["来源目录"].max_row == len(SOURCES) + 1
    return output


if __name__ == "__main__":
    path = build_workbook()
    print(f"{path} | cases={len(BATTLE_CASES)} | parameters={len(PUBLIC_PARAMETERS)} | sources={len(SOURCES)}")
